image: ubuntu

quasi_pr_build:
  tags: 
    - docker-prod
  script: echo 'Your PR is awesome'
  only:
    - external_pull_requests

quasi_master_build:
  tags: 
    - docker-prod
  script: echo 'Your master is awesome'
  only:
    - master
